### ISSUE TITLE
Add levels to spells

### ISSUE THREAD

**Issue by Otanikotani** [Otanikotani/dnd5spellbookweb#7]
Check https://github.com/servy/dnd5spellbook and add levels to spells

**Comment by tofik-mamishov** [comment]
@Otanikotani I understood what "type" is it. "Type" is a combination of level and type of the spell.
About levels. Number of levels is 9 (0-9). Zero level spell is a cantrip. So field "type" has keyword "cantrip" if spell has level 0. Another spells that have level greater than 0 have something like that "2-nd" or "8-th".
